server:
  port: 8760

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id : feign
          uri: lb://feign
          predicates:
            - Path=/feign/**
          filters:
            - StripPrefix=1
        - id: cliente
          uri: lb://cliente
          predicates:
            - Path=/cliente/**
          filters:
            - StripPrefix=1
